### ISSUE TITLE
Partial template lookups without the dash

### ISSUE THREAD

**Issue by RSSchermer** [BookingSync/broccoli-i18n-lazy-lookup#1]
I figured I'd check your opinion on this first, before creating a PR. 

I believe the Ember CLI convention for partial templates is to prefix them with a dash (e.g. `user/-form.hbs`). I'd personally prefer lazy lookups  to use a translation path without the dash (`user.form.save`, instead of `user.-form.save`). This is also how it works for Rails I believe (actually I'm not sure if Rails checks both `user._form.save` and `user.form.save` if that does not exist, but I don't think checking translation key existence is possible with this implementation).

What's your preference? Should a make a PR that implements this behavior?

**Comment by ZenCocoon** [comment]
@RSSchermer sorry for the long delay, I feel that without the `-` makes more sense, I don't see the need for the translation to know about being a partial or not.

A PR would be really welcome :)

**Comment by RSSchermer** [comment]
See PR at #3.
