### ISSUE TITLE
bound key lazy lookup

### ISSUE THREAD

**Issue by sbounmy** [BookingSync/broccoli-i18n-lazy-lookup#2]
Hello,

Basic lazy lookup is working great with string key, but what about bound key (https://github.com/jamesarosen/ember-i18n#a-translation-based-on-a-bound-key) e.g:

``` js
// components/widget.js
Ember.Component.extend({
title_i18n_key: function() {
 return '.my.title';
}
})

// templates/components/widget.hbs
{{t title_i18n_key}} //lookups for .my.title instead of components.widget.title
```

**Comment by ZenCocoon** [comment]
`title_i18n_key` should end by `Translation` to be automatically lazy looked-up. Check https://github.com/BookingSync/broccoli-i18n-lazy-lookup#in-controllers-and-components that should work as expected.

If not, please feel free to reopen the issue with more details,
Thanks,

**Comment by sbounmy** [comment]
After looking closer to the code, broccoli i18n parse files and look for translation starting by `.` and prefix directly in the js/hbs file.
My main concern was using bound keys e.g computed / binded key translation, AFAIK this won't work indeed.

**Comment by ZenCocoon** [comment]
Well it will take the translation from a bounded key just fine, but the lookup will be done from the controller location, not evaluating it from the template it self.

If that's what you where looking at, I'm afraid the current approach won't solve your issue as this is done through pre-processing.
